export const initData = {
  boards: [
    {
      id: "board-1",
      columnOrder: ["column-1", "column-2", "column-3"],
      columns: [
        {
          id: "column-1",
          boardId: "board-1",
          title: "Todo 1",
          cardOrder: ["card-1", "card-2", "card-3", "card-4"],
          cards: [
            {
              id: "card-1",
              boardId: "board-1",
              columnId: "column-1",
              title: "Title of card 1",
              image: null,
            },
            {
              id: "card-2",
              boardId: "board-1",
              columnId: "column-1",
              title: "Title of card 2",
              image: null,
            },
            {
              id: "card-3",
              boardId: "board-1",
              columnId: "column-1",
              title: "Title of card 3",
              image: null,
            },
            {
              id: "card-4",
              boardId: "board-1",
              columnId: "column-1",
              title: "Title of card 4",
              image: null,
            },
          ],
        },
        {
          id: "column-2",
          boardId: "board-1",
          title: "Todo 2",
          cardOrder: ["card-5", "card-6", "card-7", "card-8"],
          cards: [
            {
              id: "card-5",
              boardId: "board-1",
              columnId: "column-2",
              title: "Title of card 5",
              image: null,
            },
            {
              id: "card-6",
              boardId: "board-1",
              columnId: "column-2",
              title: "Title of card 6",
              image: null,
            },
            {
              id: "card-7",
              boardId: "board-1",
              columnId: "column-2",
              title: "Title of card 7",
              image: null,
            },
            {
              id: "card-8",
              boardId: "board-1",
              columnId: "column-2",
              title: "Title of card 8",
              image: null,
            },
          ],
        },
        {
          id: "column-3",
          boardId: "board-1",
          title: "Todo 3",
          cardOrder: [
            "card-9",
            "card-10",
            "card-11",
            "card-12",
            "card-13",
            "card-14",
            "card-15",
            "card-16",
            "card-17",
            "card-18",
            "card-19",
            "card-20",
          ],
          cards: [
            {
              id: "card-9",
              boardId: "board-1",
              columnId: "column-3",
              title: "Title of card 9",
              image: null,
            },
            {
              id: "card-10",
              boardId: "board-1",
              columnId: "column-3",
              title: "Title of card 10",
              image: null,
            },
            {
              id: "card-11",
              boardId: "board-1",
              columnId: "column-3",
              title: "Title of card 11",
              image: null,
            },
            {
              id: "card-12",
              boardId: "board-1",
              columnId: "column-3",
              title: "Title of card 12",
              image: null,
            },
            {
              id: "card-13",
              boardId: "board-1",
              columnId: "column-3",
              title: "Title of card 13",
              image: null,
            },
            {
              id: "card-14",
              boardId: "board-1",
              columnId: "column-3",
              title: "Title of card 14",
              image: null,
            },
            {
              id: "card-15",
              boardId: "board-1",
              columnId: "column-3",
              title: "Title of card 15",
              image: null,
            },
            {
              id: "card-16",
              boardId: "board-1",
              columnId: "column-3",
              title: "Title of card 16",
              image: null,
            },
            {
              id: "card-17",
              boardId: "board-1",
              columnId: "column-3",
              title: "Title of card 17",
              image: null,
            },
            {
              id: "card-18",
              boardId: "board-1",
              columnId: "column-3",
              title: "Title of card 18",
              image: null,
            },
            {
              id: "card-19",
              boardId: "board-1",
              columnId: "column-3",
              title: "Title of card 19",
              image: null,
            },
            {
              id: "card-20",
              boardId: "board-1",
              columnId: "column-3",
              title: "Title of card 20",
              image: null,
            },
          ],
        },
      ],
    },
  ],
};

export const collectionsTest = {
  collection: {
    collectionOrder: [
      "3d7b1771-b6c8-47bb-91e5-2cd932aa1708",
      "74a1480f-ef44-487b-899e-5b9400000b63",
    ],
    collections: [
      {
        id: "3d7b1771-b6c8-47bb-91e5-2cd932aa1708",
        title: "Collection Test 1",
        labelColor: "green",
        boards: [
          {
            id: "board-1",
            columnOrder: ["column-1", "column-2", "column-3"],
            columns: [
              {
                id: "column-1",
                boardId: "board-1",
                title: "Todo 1",
                cardOrder: ["card-1", "card-2", "card-3", "card-4"],
                cards: [
                  {
                    id: "card-1",
                    boardId: "board-1",
                    columnId: "column-1",
                    title: "Title of card 1",
                    image: null,
                  },
                  {
                    id: "card-2",
                    boardId: "board-1",
                    columnId: "column-1",
                    title: "Title of card 2",
                    image: null,
                  },
                  {
                    id: "card-3",
                    boardId: "board-1",
                    columnId: "column-1",
                    title: "Title of card 3",
                    image: null,
                  },
                  {
                    id: "card-4",
                    boardId: "board-1",
                    columnId: "column-1",
                    title: "Title of card 4",
                    image: null,
                  },
                ],
              },
              {
                id: "column-2",
                boardId: "board-1",
                title: "Todo 2",
                cardOrder: ["card-5", "card-6", "card-7", "card-8"],
                cards: [
                  {
                    id: "card-5",
                    boardId: "board-1",
                    columnId: "column-2",
                    title: "Title of card 5",
                    image: null,
                  },
                  {
                    id: "card-6",
                    boardId: "board-1",
                    columnId: "column-2",
                    title: "Title of card 6",
                    image: null,
                  },
                  {
                    id: "card-7",
                    boardId: "board-1",
                    columnId: "column-2",
                    title: "Title of card 7",
                    image: null,
                  },
                  {
                    id: "card-8",
                    boardId: "board-1",
                    columnId: "column-2",
                    title: "Title of card 8",
                    image: null,
                  },
                ],
              },
              {
                id: "column-3",
                boardId: "board-1",
                title: "Todo 3",
                cardOrder: [
                  "card-9",
                  "card-10",
                  "card-11",
                  "card-12",
                  "card-13",
                  "card-14",
                  "card-15",
                  "card-16",
                  "card-17",
                  "card-18",
                  "card-19",
                  "card-20",
                ],
                cards: [
                  {
                    id: "card-9",
                    boardId: "board-1",
                    columnId: "column-3",
                    title: "Title of card 9",
                    image: null,
                  },
                  {
                    id: "card-10",
                    boardId: "board-1",
                    columnId: "column-3",
                    title: "Title of card 10",
                    image: null,
                  },
                  {
                    id: "card-11",
                    boardId: "board-1",
                    columnId: "column-3",
                    title: "Title of card 11",
                    image: null,
                  },
                  {
                    id: "card-12",
                    boardId: "board-1",
                    columnId: "column-3",
                    title: "Title of card 12",
                    image: null,
                  },
                  {
                    id: "card-13",
                    boardId: "board-1",
                    columnId: "column-3",
                    title: "Title of card 13",
                    image: null,
                  },
                  {
                    id: "card-14",
                    boardId: "board-1",
                    columnId: "column-3",
                    title: "Title of card 14",
                    image: null,
                  },
                  {
                    id: "card-15",
                    boardId: "board-1",
                    columnId: "column-3",
                    title: "Title of card 15",
                    image: null,
                  },
                  {
                    id: "card-16",
                    boardId: "board-1",
                    columnId: "column-3",
                    title: "Title of card 16",
                    image: null,
                  },
                  {
                    id: "card-17",
                    boardId: "board-1",
                    columnId: "column-3",
                    title: "Title of card 17",
                    image: null,
                  },
                  {
                    id: "card-18",
                    boardId: "board-1",
                    columnId: "column-3",
                    title: "Title of card 18",
                    image: null,
                  },
                  {
                    id: "card-19",
                    boardId: "board-1",
                    columnId: "column-3",
                    title: "Title of card 19",
                    image: null,
                  },
                  {
                    id: "card-20",
                    boardId: "board-1",
                    columnId: "column-3",
                    title: "Title of card 20",
                    image: null,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "74a1480f-ef44-487b-899e-5b9400000b63",
        title: "Collection Test 2",
        labelColor: "green",
        boards: [
          {
            id: "board-1",
            columnOrder: ["column-1", "column-2"],
            columns: [
              {
                id: "column-1",
                boardId: "board-1",
                title: "Todo 1",
                cardOrder: ["card-1", "card-2", "card-3", "card-4"],
                cards: [
                  {
                    id: "card-1",
                    boardId: "board-1",
                    columnId: "column-1",
                    title: "Title of card 1",
                    image: null,
                  },
                  {
                    id: "card-2",
                    boardId: "board-1",
                    columnId: "column-1",
                    title: "Title of card 2",
                    image: null,
                  },
                  {
                    id: "card-3",
                    boardId: "board-1",
                    columnId: "column-1",
                    title: "Title of card 3",
                    image: null,
                  },
                  {
                    id: "card-4",
                    boardId: "board-1",
                    columnId: "column-1",
                    title: "Title of card 4",
                    image: null,
                  },
                ],
              },
              {
                id: "column-2",
                boardId: "board-1",
                title: "Todo 2",
                cardOrder: ["card-5", "card-6", "card-7", "card-8"],
                cards: [
                  {
                    id: "card-5",
                    boardId: "board-1",
                    columnId: "column-2",
                    title: "Title of card 5",
                    image: null,
                  },
                  {
                    id: "card-6",
                    boardId: "board-1",
                    columnId: "column-2",
                    title: "Title of card 6",
                    image: null,
                  },
                  {
                    id: "card-7",
                    boardId: "board-1",
                    columnId: "column-2",
                    title: "Title of card 7",
                    image: null,
                  },
                  {
                    id: "card-8",
                    boardId: "board-1",
                    columnId: "column-2",
                    title: "Title of card 8",
                    image: null,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
};
